### PR TITLE
Added --version flag

### LINKED ISSUE #26: Add `version` command

### PR DESCRIPTION
**Pull request by jdewinne**
Fixes #26 (using the flag `-v` or `--version`)

### CODE REVIEW

**Comment by xavpaice** [comment]
Is it possible to create a versioning similar to how we do this in Troubleshoot with "github.com/replicatedhq/troubleshoot/pkg/version"? Also, in Troubleshoot we use `support-bundle version` rather than `--version`, reserving `-v` for verbose.

FWIW we're planning to include this repo in the Troubleshoot repo (hence the need for consistency).

**Comment by jdewinne** [comment]
This uses the default from cobra. So making it a command would deviate from that. But can of course be done.

**Comment by banjoh** [comment]
I'm also leaning towards `version` command instead of GNU's `--version` flag mainly cause of 2 reasons.

1. It seems to be the preferred way tools follow in k8s ecosystem e.g helm, kompose, kubectl crictl..... Some out there may defer of course like prometheus, but still :)
2. There is a [thought of adopting](https://github.com/replicatedhq/troubleshoot/issues/922) `klog` logging library which gives us log levels that use `-v=3` like flags to allow increasing/decreasing the amount of logging printed out. If we use `--version/-v`, we rule out any opportunity of adopting the lib

**Comment by xavpaice** [comment]
Closing, we won't merge this in preference of a `version` subcommand. https://github.com/replicatedhq/troubleshoot/issues/933 will handle that.

**Pull request closed without merging**
